// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbtaolycccmmqmwurinp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBidGFvbHljY2NtbXFtd3VyaW5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTAzMzIsImV4cCI6MjA2NTc2NjMzMn0.yRMyz5je_YUJCgpwi-cbx8G-yocjfriRfyliTtk5p28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    headers: {
      'Accept': 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'Prefer': 'return=representation',
      'apikey': SUPABASE_PUBLISHABLE_KEY,
    },
  },
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  },
  db: {
    schema: 'public',
  },
});